#! /bin/bash

# Kong Installer for debian and ubuntu

#Update & Upgrade System
echo "Update & Upgrade System"
apt update && apt upgrade -y
apt install wget git curl postgresql net-tools -y
#Install Kong
echo "Install Kong\n"
curl -Lo kong-3.8.0.deb "https://packages.konghq.com/public/gateway-38/deb/debian/pool/bullseye/main/k/ko/kong_3.8.0/kong_3.8.0_$(dpkg --print-architecture).deb"
apt install -y ./kong-3.8.0.deb
cp kong.conf /etc/kong
echo "Prepare The Database...."
sleep 3
# su - postgres
# psql -c "CREATE USER kong4 WITH PASSWORD 'super_secret';" -c "CREATE DATABASE kong4 OWNER kong4;"
su -c "psql -d postgres -c \"CREATE USER kong WITH PASSWORD 'super_secret'\"" postgres
su -c "psql -d postgres -c \"CREATE DATABASE kong OWNER kong\"" postgres
# exit
echo "Start Kong Database Migration...."
sleep 3
kong migrations bootstrap -c /etc/kong/kong.conf
echo "Start Kong"
sleep 3
kong start -c /etc/kong/kong.conf
#instalation Done
netstat -tulpn
echo "Installation Done........."
echo "Kong Proxy"
echo "http://ip-server:80"
echo "Kong Admin API"
echo "http://ip-server:8001"
echo "Kong Manager"
echo "http://ip-server:8002"
